// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worldstate.proto

package uk.ac.ed.inf.sdp.group4;

public final class Worldstate {
  private Worldstate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class WorldObject extends
      com.google.protobuf.GeneratedMessage {
    // Use WorldObject.newBuilder() to construct.
    private WorldObject() {
      initFields();
    }
    private WorldObject(boolean noInit) {}
    
    private static final WorldObject defaultInstance;
    public static WorldObject getDefaultInstance() {
      return defaultInstance;
    }
    
    public WorldObject getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_fieldAccessorTable;
    }
    
    public static final class Position extends
        com.google.protobuf.GeneratedMessage {
      // Use Position.newBuilder() to construct.
      private Position() {
        initFields();
      }
      private Position(boolean noInit) {}
      
      private static final Position defaultInstance;
      public static Position getDefaultInstance() {
        return defaultInstance;
      }
      
      public Position getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_fieldAccessorTable;
      }
      
      // required int32 x = 1;
      public static final int X_FIELD_NUMBER = 1;
      private boolean hasX;
      private int x_ = 0;
      public boolean hasX() { return hasX; }
      public int getX() { return x_; }
      
      // required int32 y = 2;
      public static final int Y_FIELD_NUMBER = 2;
      private boolean hasY;
      private int y_ = 0;
      public boolean hasY() { return hasY; }
      public int getY() { return y_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasX) return false;
        if (!hasY) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasX()) {
          output.writeInt32(1, getX());
        }
        if (hasY()) {
          output.writeInt32(2, getY());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasX()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, getX());
        }
        if (hasY()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, getY());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position result;
        
        // Construct using uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position();
          return builder;
        }
        
        protected uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDescriptor();
        }
        
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position getDefaultInstanceForType() {
          return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position) {
            return mergeFrom((uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position other) {
          if (other == uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setX(input.readInt32());
                break;
              }
              case 16: {
                setY(input.readInt32());
                break;
              }
            }
          }
        }
        
        
        // required int32 x = 1;
        public boolean hasX() {
          return result.hasX();
        }
        public int getX() {
          return result.getX();
        }
        public Builder setX(int value) {
          result.hasX = true;
          result.x_ = value;
          return this;
        }
        public Builder clearX() {
          result.hasX = false;
          result.x_ = 0;
          return this;
        }
        
        // required int32 y = 2;
        public boolean hasY() {
          return result.hasY();
        }
        public int getY() {
          return result.getY();
        }
        public Builder setY(int value) {
          result.hasY = true;
          result.y_ = value;
          return this;
        }
        public Builder clearY() {
          result.hasY = false;
          result.y_ = 0;
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:uk.ac.ed.inf.sdp.group4.WorldObject.Position)
      }
      
      static {
        defaultInstance = new Position(true);
        uk.ac.ed.inf.sdp.group4.Worldstate.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:uk.ac.ed.inf.sdp.group4.WorldObject.Position)
    }
    
    public static final class Velocity extends
        com.google.protobuf.GeneratedMessage {
      // Use Velocity.newBuilder() to construct.
      private Velocity() {
        initFields();
      }
      private Velocity(boolean noInit) {}
      
      private static final Velocity defaultInstance;
      public static Velocity getDefaultInstance() {
        return defaultInstance;
      }
      
      public Velocity getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Velocity_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Velocity_fieldAccessorTable;
      }
      
      // optional int32 direction = 1;
      public static final int DIRECTION_FIELD_NUMBER = 1;
      private boolean hasDirection;
      private int direction_ = 0;
      public boolean hasDirection() { return hasDirection; }
      public int getDirection() { return direction_; }
      
      // optional float magnitude = 2;
      public static final int MAGNITUDE_FIELD_NUMBER = 2;
      private boolean hasMagnitude;
      private float magnitude_ = 0F;
      public boolean hasMagnitude() { return hasMagnitude; }
      public float getMagnitude() { return magnitude_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasDirection()) {
          output.writeInt32(1, getDirection());
        }
        if (hasMagnitude()) {
          output.writeFloat(2, getMagnitude());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasDirection()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, getDirection());
        }
        if (hasMagnitude()) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, getMagnitude());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity result;
        
        // Construct using uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity();
          return builder;
        }
        
        protected uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.getDescriptor();
        }
        
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity getDefaultInstanceForType() {
          return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity) {
            return mergeFrom((uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity other) {
          if (other == uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.getDefaultInstance()) return this;
          if (other.hasDirection()) {
            setDirection(other.getDirection());
          }
          if (other.hasMagnitude()) {
            setMagnitude(other.getMagnitude());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setDirection(input.readInt32());
                break;
              }
              case 21: {
                setMagnitude(input.readFloat());
                break;
              }
            }
          }
        }
        
        
        // optional int32 direction = 1;
        public boolean hasDirection() {
          return result.hasDirection();
        }
        public int getDirection() {
          return result.getDirection();
        }
        public Builder setDirection(int value) {
          result.hasDirection = true;
          result.direction_ = value;
          return this;
        }
        public Builder clearDirection() {
          result.hasDirection = false;
          result.direction_ = 0;
          return this;
        }
        
        // optional float magnitude = 2;
        public boolean hasMagnitude() {
          return result.hasMagnitude();
        }
        public float getMagnitude() {
          return result.getMagnitude();
        }
        public Builder setMagnitude(float value) {
          result.hasMagnitude = true;
          result.magnitude_ = value;
          return this;
        }
        public Builder clearMagnitude() {
          result.hasMagnitude = false;
          result.magnitude_ = 0F;
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:uk.ac.ed.inf.sdp.group4.WorldObject.Velocity)
      }
      
      static {
        defaultInstance = new Velocity(true);
        uk.ac.ed.inf.sdp.group4.Worldstate.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:uk.ac.ed.inf.sdp.group4.WorldObject.Velocity)
    }
    
    // required .uk.ac.ed.inf.sdp.group4.WorldObject.Position position = 1;
    public static final int POSITION_FIELD_NUMBER = 1;
    private boolean hasPosition;
    private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position position_;
    public boolean hasPosition() { return hasPosition; }
    public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position getPosition() { return position_; }
    
    // required .uk.ac.ed.inf.sdp.group4.WorldObject.Velocity velocity = 2;
    public static final int VELOCITY_FIELD_NUMBER = 2;
    private boolean hasVelocity;
    private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity velocity_;
    public boolean hasVelocity() { return hasVelocity; }
    public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity getVelocity() { return velocity_; }
    
    // optional int32 rotation = 3;
    public static final int ROTATION_FIELD_NUMBER = 3;
    private boolean hasRotation;
    private int rotation_ = 0;
    public boolean hasRotation() { return hasRotation; }
    public int getRotation() { return rotation_; }
    
    private void initFields() {
      position_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDefaultInstance();
      velocity_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasPosition) return false;
      if (!hasVelocity) return false;
      if (!getPosition().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPosition()) {
        output.writeMessage(1, getPosition());
      }
      if (hasVelocity()) {
        output.writeMessage(2, getVelocity());
      }
      if (hasRotation()) {
        output.writeInt32(3, getRotation());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPosition()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPosition());
      }
      if (hasVelocity()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getVelocity());
      }
      if (hasRotation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getRotation());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject result;
      
      // Construct using uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject();
        return builder;
      }
      
      protected uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDescriptor();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getDefaultInstanceForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject) {
          return mergeFrom((uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject other) {
        if (other == uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance()) return this;
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.hasVelocity()) {
          mergeVelocity(other.getVelocity());
        }
        if (other.hasRotation()) {
          setRotation(other.getRotation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.Builder subBuilder = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.newBuilder();
              if (hasPosition()) {
                subBuilder.mergeFrom(getPosition());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPosition(subBuilder.buildPartial());
              break;
            }
            case 18: {
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.Builder subBuilder = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.newBuilder();
              if (hasVelocity()) {
                subBuilder.mergeFrom(getVelocity());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setVelocity(subBuilder.buildPartial());
              break;
            }
            case 24: {
              setRotation(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required .uk.ac.ed.inf.sdp.group4.WorldObject.Position position = 1;
      public boolean hasPosition() {
        return result.hasPosition();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position getPosition() {
        return result.getPosition();
      }
      public Builder setPosition(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPosition = true;
        result.position_ = value;
        return this;
      }
      public Builder setPosition(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.Builder builderForValue) {
        result.hasPosition = true;
        result.position_ = builderForValue.build();
        return this;
      }
      public Builder mergePosition(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position value) {
        if (result.hasPosition() &&
            result.position_ != uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDefaultInstance()) {
          result.position_ =
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.newBuilder(result.position_).mergeFrom(value).buildPartial();
        } else {
          result.position_ = value;
        }
        result.hasPosition = true;
        return this;
      }
      public Builder clearPosition() {
        result.hasPosition = false;
        result.position_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDefaultInstance();
        return this;
      }
      
      // required .uk.ac.ed.inf.sdp.group4.WorldObject.Velocity velocity = 2;
      public boolean hasVelocity() {
        return result.hasVelocity();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity getVelocity() {
        return result.getVelocity();
      }
      public Builder setVelocity(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasVelocity = true;
        result.velocity_ = value;
        return this;
      }
      public Builder setVelocity(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.Builder builderForValue) {
        result.hasVelocity = true;
        result.velocity_ = builderForValue.build();
        return this;
      }
      public Builder mergeVelocity(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity value) {
        if (result.hasVelocity() &&
            result.velocity_ != uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.getDefaultInstance()) {
          result.velocity_ =
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.newBuilder(result.velocity_).mergeFrom(value).buildPartial();
        } else {
          result.velocity_ = value;
        }
        result.hasVelocity = true;
        return this;
      }
      public Builder clearVelocity() {
        result.hasVelocity = false;
        result.velocity_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.getDefaultInstance();
        return this;
      }
      
      // optional int32 rotation = 3;
      public boolean hasRotation() {
        return result.hasRotation();
      }
      public int getRotation() {
        return result.getRotation();
      }
      public Builder setRotation(int value) {
        result.hasRotation = true;
        result.rotation_ = value;
        return this;
      }
      public Builder clearRotation() {
        result.hasRotation = false;
        result.rotation_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:uk.ac.ed.inf.sdp.group4.WorldObject)
    }
    
    static {
      defaultInstance = new WorldObject(true);
      uk.ac.ed.inf.sdp.group4.Worldstate.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:uk.ac.ed.inf.sdp.group4.WorldObject)
  }
  
  public static final class WorldStateResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use WorldStateResponse.newBuilder() to construct.
    private WorldStateResponse() {
      initFields();
    }
    private WorldStateResponse(boolean noInit) {}
    
    private static final WorldStateResponse defaultInstance;
    public static WorldStateResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public WorldStateResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_fieldAccessorTable;
    }
    
    // required bool changed = 1;
    public static final int CHANGED_FIELD_NUMBER = 1;
    private boolean hasChanged;
    private boolean changed_ = false;
    public boolean hasChanged() { return hasChanged; }
    public boolean getChanged() { return changed_; }
    
    // required uint64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // optional .uk.ac.ed.inf.sdp.group4.WorldObject ball = 3;
    public static final int BALL_FIELD_NUMBER = 3;
    private boolean hasBall;
    private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject ball_;
    public boolean hasBall() { return hasBall; }
    public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getBall() { return ball_; }
    
    // optional .uk.ac.ed.inf.sdp.group4.WorldObject blue = 4;
    public static final int BLUE_FIELD_NUMBER = 4;
    private boolean hasBlue;
    private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject blue_;
    public boolean hasBlue() { return hasBlue; }
    public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getBlue() { return blue_; }
    
    // optional .uk.ac.ed.inf.sdp.group4.WorldObject yellow = 5;
    public static final int YELLOW_FIELD_NUMBER = 5;
    private boolean hasYellow;
    private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject yellow_;
    public boolean hasYellow() { return hasYellow; }
    public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getYellow() { return yellow_; }
    
    private void initFields() {
      ball_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
      blue_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
      yellow_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasChanged) return false;
      if (!hasTimestamp) return false;
      if (hasBall()) {
        if (!getBall().isInitialized()) return false;
      }
      if (hasBlue()) {
        if (!getBlue().isInitialized()) return false;
      }
      if (hasYellow()) {
        if (!getYellow().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasChanged()) {
        output.writeBool(1, getChanged());
      }
      if (hasTimestamp()) {
        output.writeUInt64(2, getTimestamp());
      }
      if (hasBall()) {
        output.writeMessage(3, getBall());
      }
      if (hasBlue()) {
        output.writeMessage(4, getBlue());
      }
      if (hasYellow()) {
        output.writeMessage(5, getYellow());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasChanged()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getChanged());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, getTimestamp());
      }
      if (hasBall()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBall());
      }
      if (hasBlue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getBlue());
      }
      if (hasYellow()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getYellow());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse result;
      
      // Construct using uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse();
        return builder;
      }
      
      protected uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDescriptor();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse getDefaultInstanceForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse) {
          return mergeFrom((uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse other) {
        if (other == uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDefaultInstance()) return this;
        if (other.hasChanged()) {
          setChanged(other.getChanged());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasBall()) {
          mergeBall(other.getBall());
        }
        if (other.hasBlue()) {
          mergeBlue(other.getBlue());
        }
        if (other.hasYellow()) {
          mergeYellow(other.getYellow());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setChanged(input.readBool());
              break;
            }
            case 16: {
              setTimestamp(input.readUInt64());
              break;
            }
            case 26: {
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder subBuilder = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder();
              if (hasBall()) {
                subBuilder.mergeFrom(getBall());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBall(subBuilder.buildPartial());
              break;
            }
            case 34: {
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder subBuilder = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder();
              if (hasBlue()) {
                subBuilder.mergeFrom(getBlue());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBlue(subBuilder.buildPartial());
              break;
            }
            case 42: {
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder subBuilder = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder();
              if (hasYellow()) {
                subBuilder.mergeFrom(getYellow());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setYellow(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required bool changed = 1;
      public boolean hasChanged() {
        return result.hasChanged();
      }
      public boolean getChanged() {
        return result.getChanged();
      }
      public Builder setChanged(boolean value) {
        result.hasChanged = true;
        result.changed_ = value;
        return this;
      }
      public Builder clearChanged() {
        result.hasChanged = false;
        result.changed_ = false;
        return this;
      }
      
      // required uint64 timestamp = 2;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // optional .uk.ac.ed.inf.sdp.group4.WorldObject ball = 3;
      public boolean hasBall() {
        return result.hasBall();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getBall() {
        return result.getBall();
      }
      public Builder setBall(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasBall = true;
        result.ball_ = value;
        return this;
      }
      public Builder setBall(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder builderForValue) {
        result.hasBall = true;
        result.ball_ = builderForValue.build();
        return this;
      }
      public Builder mergeBall(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (result.hasBall() &&
            result.ball_ != uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance()) {
          result.ball_ =
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder(result.ball_).mergeFrom(value).buildPartial();
        } else {
          result.ball_ = value;
        }
        result.hasBall = true;
        return this;
      }
      public Builder clearBall() {
        result.hasBall = false;
        result.ball_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
        return this;
      }
      
      // optional .uk.ac.ed.inf.sdp.group4.WorldObject blue = 4;
      public boolean hasBlue() {
        return result.hasBlue();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getBlue() {
        return result.getBlue();
      }
      public Builder setBlue(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasBlue = true;
        result.blue_ = value;
        return this;
      }
      public Builder setBlue(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder builderForValue) {
        result.hasBlue = true;
        result.blue_ = builderForValue.build();
        return this;
      }
      public Builder mergeBlue(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (result.hasBlue() &&
            result.blue_ != uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance()) {
          result.blue_ =
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder(result.blue_).mergeFrom(value).buildPartial();
        } else {
          result.blue_ = value;
        }
        result.hasBlue = true;
        return this;
      }
      public Builder clearBlue() {
        result.hasBlue = false;
        result.blue_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
        return this;
      }
      
      // optional .uk.ac.ed.inf.sdp.group4.WorldObject yellow = 5;
      public boolean hasYellow() {
        return result.hasYellow();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getYellow() {
        return result.getYellow();
      }
      public Builder setYellow(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasYellow = true;
        result.yellow_ = value;
        return this;
      }
      public Builder setYellow(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder builderForValue) {
        result.hasYellow = true;
        result.yellow_ = builderForValue.build();
        return this;
      }
      public Builder mergeYellow(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (result.hasYellow() &&
            result.yellow_ != uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance()) {
          result.yellow_ =
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder(result.yellow_).mergeFrom(value).buildPartial();
        } else {
          result.yellow_ = value;
        }
        result.hasYellow = true;
        return this;
      }
      public Builder clearYellow() {
        result.hasYellow = false;
        result.yellow_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:uk.ac.ed.inf.sdp.group4.WorldStateResponse)
    }
    
    static {
      defaultInstance = new WorldStateResponse(true);
      uk.ac.ed.inf.sdp.group4.Worldstate.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:uk.ac.ed.inf.sdp.group4.WorldStateResponse)
  }
  
  public static final class WorldStateRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use WorldStateRequest.newBuilder() to construct.
    private WorldStateRequest() {
      initFields();
    }
    private WorldStateRequest(boolean noInit) {}
    
    private static final WorldStateRequest defaultInstance;
    public static WorldStateRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public WorldStateRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_fieldAccessorTable;
    }
    
    // required uint64 last_timestamp = 1;
    public static final int LAST_TIMESTAMP_FIELD_NUMBER = 1;
    private boolean hasLastTimestamp;
    private long lastTimestamp_ = 0L;
    public boolean hasLastTimestamp() { return hasLastTimestamp; }
    public long getLastTimestamp() { return lastTimestamp_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasLastTimestamp) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLastTimestamp()) {
        output.writeUInt64(1, getLastTimestamp());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLastTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getLastTimestamp());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest result;
      
      // Construct using uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest();
        return builder;
      }
      
      protected uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.getDescriptor();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest getDefaultInstanceForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest) {
          return mergeFrom((uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest other) {
        if (other == uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.getDefaultInstance()) return this;
        if (other.hasLastTimestamp()) {
          setLastTimestamp(other.getLastTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setLastTimestamp(input.readUInt64());
              break;
            }
          }
        }
      }
      
      
      // required uint64 last_timestamp = 1;
      public boolean hasLastTimestamp() {
        return result.hasLastTimestamp();
      }
      public long getLastTimestamp() {
        return result.getLastTimestamp();
      }
      public Builder setLastTimestamp(long value) {
        result.hasLastTimestamp = true;
        result.lastTimestamp_ = value;
        return this;
      }
      public Builder clearLastTimestamp() {
        result.hasLastTimestamp = false;
        result.lastTimestamp_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:uk.ac.ed.inf.sdp.group4.WorldStateRequest)
    }
    
    static {
      defaultInstance = new WorldStateRequest(true);
      uk.ac.ed.inf.sdp.group4.Worldstate.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:uk.ac.ed.inf.sdp.group4.WorldStateRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Velocity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Velocity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020worldstate.proto\022\027uk.ac.ed.inf.sdp.gro" +
      "up4\"\365\001\n\013WorldObject\022?\n\010position\030\001 \002(\0132-." +
      "uk.ac.ed.inf.sdp.group4.WorldObject.Posi" +
      "tion\022?\n\010velocity\030\002 \002(\0132-.uk.ac.ed.inf.sd" +
      "p.group4.WorldObject.Velocity\022\020\n\010rotatio" +
      "n\030\003 \001(\005\032 \n\010Position\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(" +
      "\005\0320\n\010Velocity\022\021\n\tdirection\030\001 \001(\005\022\021\n\tmagn" +
      "itude\030\002 \001(\002\"\326\001\n\022WorldStateResponse\022\017\n\007ch" +
      "anged\030\001 \002(\010\022\021\n\ttimestamp\030\002 \002(\004\0222\n\004ball\030\003" +
      " \001(\0132$.uk.ac.ed.inf.sdp.group4.WorldObje",
      "ct\0222\n\004blue\030\004 \001(\0132$.uk.ac.ed.inf.sdp.grou" +
      "p4.WorldObject\0224\n\006yellow\030\005 \001(\0132$.uk.ac.e" +
      "d.inf.sdp.group4.WorldObject\"+\n\021WorldSta" +
      "teRequest\022\026\n\016last_timestamp\030\001 \002(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor,
              new java.lang.String[] { "Position", "Velocity", "Rotation", },
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.class,
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder.class);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_descriptor =
            internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor.getNestedTypes().get(0);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_descriptor,
              new java.lang.String[] { "X", "Y", },
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.class,
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.Builder.class);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Velocity_descriptor =
            internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor.getNestedTypes().get(1);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Velocity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Velocity_descriptor,
              new java.lang.String[] { "Direction", "Magnitude", },
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.class,
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Velocity.Builder.class);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_descriptor,
              new java.lang.String[] { "Changed", "Timestamp", "Ball", "Blue", "Yellow", },
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.class,
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.Builder.class);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_descriptor,
              new java.lang.String[] { "LastTimestamp", },
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.class,
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
