// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worldstate.proto

package uk.ac.ed.inf.sdp.group4;

public final class Worldstate {
  private Worldstate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class WorldObject extends
      com.google.protobuf.GeneratedMessage {
    // Use WorldObject.newBuilder() to construct.
    private WorldObject() {
      initFields();
    }
    private WorldObject(boolean noInit) {}
    
    private static final WorldObject defaultInstance;
    public static WorldObject getDefaultInstance() {
      return defaultInstance;
    }
    
    public WorldObject getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_fieldAccessorTable;
    }
    
    public static final class Position extends
        com.google.protobuf.GeneratedMessage {
      // Use Position.newBuilder() to construct.
      private Position() {
        initFields();
      }
      private Position(boolean noInit) {}
      
      private static final Position defaultInstance;
      public static Position getDefaultInstance() {
        return defaultInstance;
      }
      
      public Position getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_fieldAccessorTable;
      }
      
      // required int32 x = 1;
      public static final int X_FIELD_NUMBER = 1;
      private boolean hasX;
      private int x_ = 0;
      public boolean hasX() { return hasX; }
      public int getX() { return x_; }
      
      // required int32 y = 2;
      public static final int Y_FIELD_NUMBER = 2;
      private boolean hasY;
      private int y_ = 0;
      public boolean hasY() { return hasY; }
      public int getY() { return y_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasX) return false;
        if (!hasY) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasX()) {
          output.writeInt32(1, getX());
        }
        if (hasY()) {
          output.writeInt32(2, getY());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasX()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, getX());
        }
        if (hasY()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, getY());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position result;
        
        // Construct using uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position();
          return builder;
        }
        
        protected uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDescriptor();
        }
        
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position getDefaultInstanceForType() {
          return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position) {
            return mergeFrom((uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position other) {
          if (other == uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setX(input.readInt32());
                break;
              }
              case 16: {
                setY(input.readInt32());
                break;
              }
            }
          }
        }
        
        
        // required int32 x = 1;
        public boolean hasX() {
          return result.hasX();
        }
        public int getX() {
          return result.getX();
        }
        public Builder setX(int value) {
          result.hasX = true;
          result.x_ = value;
          return this;
        }
        public Builder clearX() {
          result.hasX = false;
          result.x_ = 0;
          return this;
        }
        
        // required int32 y = 2;
        public boolean hasY() {
          return result.hasY();
        }
        public int getY() {
          return result.getY();
        }
        public Builder setY(int value) {
          result.hasY = true;
          result.y_ = value;
          return this;
        }
        public Builder clearY() {
          result.hasY = false;
          result.y_ = 0;
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:uk.ac.ed.inf.sdp.group4.WorldObject.Position)
      }
      
      static {
        defaultInstance = new Position(true);
        uk.ac.ed.inf.sdp.group4.Worldstate.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:uk.ac.ed.inf.sdp.group4.WorldObject.Position)
    }
    
    public static final class Vector extends
        com.google.protobuf.GeneratedMessage {
      // Use Vector.newBuilder() to construct.
      private Vector() {
        initFields();
      }
      private Vector(boolean noInit) {}
      
      private static final Vector defaultInstance;
      public static Vector getDefaultInstance() {
        return defaultInstance;
      }
      
      public Vector getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Vector_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Vector_fieldAccessorTable;
      }
      
      // required int32 direction = 1;
      public static final int DIRECTION_FIELD_NUMBER = 1;
      private boolean hasDirection;
      private int direction_ = 0;
      public boolean hasDirection() { return hasDirection; }
      public int getDirection() { return direction_; }
      
      // optional float velocity = 2;
      public static final int VELOCITY_FIELD_NUMBER = 2;
      private boolean hasVelocity;
      private float velocity_ = 0F;
      public boolean hasVelocity() { return hasVelocity; }
      public float getVelocity() { return velocity_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasDirection) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasDirection()) {
          output.writeInt32(1, getDirection());
        }
        if (hasVelocity()) {
          output.writeFloat(2, getVelocity());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasDirection()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, getDirection());
        }
        if (hasVelocity()) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, getVelocity());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector result;
        
        // Construct using uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector();
          return builder;
        }
        
        protected uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.getDescriptor();
        }
        
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector getDefaultInstanceForType() {
          return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector) {
            return mergeFrom((uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector other) {
          if (other == uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.getDefaultInstance()) return this;
          if (other.hasDirection()) {
            setDirection(other.getDirection());
          }
          if (other.hasVelocity()) {
            setVelocity(other.getVelocity());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setDirection(input.readInt32());
                break;
              }
              case 21: {
                setVelocity(input.readFloat());
                break;
              }
            }
          }
        }
        
        
        // required int32 direction = 1;
        public boolean hasDirection() {
          return result.hasDirection();
        }
        public int getDirection() {
          return result.getDirection();
        }
        public Builder setDirection(int value) {
          result.hasDirection = true;
          result.direction_ = value;
          return this;
        }
        public Builder clearDirection() {
          result.hasDirection = false;
          result.direction_ = 0;
          return this;
        }
        
        // optional float velocity = 2;
        public boolean hasVelocity() {
          return result.hasVelocity();
        }
        public float getVelocity() {
          return result.getVelocity();
        }
        public Builder setVelocity(float value) {
          result.hasVelocity = true;
          result.velocity_ = value;
          return this;
        }
        public Builder clearVelocity() {
          result.hasVelocity = false;
          result.velocity_ = 0F;
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:uk.ac.ed.inf.sdp.group4.WorldObject.Vector)
      }
      
      static {
        defaultInstance = new Vector(true);
        uk.ac.ed.inf.sdp.group4.Worldstate.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:uk.ac.ed.inf.sdp.group4.WorldObject.Vector)
    }
    
    // required .uk.ac.ed.inf.sdp.group4.WorldObject.Position position = 1;
    public static final int POSITION_FIELD_NUMBER = 1;
    private boolean hasPosition;
    private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position position_;
    public boolean hasPosition() { return hasPosition; }
    public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position getPosition() { return position_; }
    
    // optional .uk.ac.ed.inf.sdp.group4.WorldObject.Vector vector = 2;
    public static final int VECTOR_FIELD_NUMBER = 2;
    private boolean hasVector;
    private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector vector_;
    public boolean hasVector() { return hasVector; }
    public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector getVector() { return vector_; }
    
    private void initFields() {
      position_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDefaultInstance();
      vector_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasPosition) return false;
      if (!getPosition().isInitialized()) return false;
      if (hasVector()) {
        if (!getVector().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPosition()) {
        output.writeMessage(1, getPosition());
      }
      if (hasVector()) {
        output.writeMessage(2, getVector());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPosition()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPosition());
      }
      if (hasVector()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getVector());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject result;
      
      // Construct using uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject();
        return builder;
      }
      
      protected uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDescriptor();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getDefaultInstanceForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject) {
          return mergeFrom((uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject other) {
        if (other == uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance()) return this;
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.hasVector()) {
          mergeVector(other.getVector());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.Builder subBuilder = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.newBuilder();
              if (hasPosition()) {
                subBuilder.mergeFrom(getPosition());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPosition(subBuilder.buildPartial());
              break;
            }
            case 18: {
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.Builder subBuilder = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.newBuilder();
              if (hasVector()) {
                subBuilder.mergeFrom(getVector());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setVector(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .uk.ac.ed.inf.sdp.group4.WorldObject.Position position = 1;
      public boolean hasPosition() {
        return result.hasPosition();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position getPosition() {
        return result.getPosition();
      }
      public Builder setPosition(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPosition = true;
        result.position_ = value;
        return this;
      }
      public Builder setPosition(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.Builder builderForValue) {
        result.hasPosition = true;
        result.position_ = builderForValue.build();
        return this;
      }
      public Builder mergePosition(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position value) {
        if (result.hasPosition() &&
            result.position_ != uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDefaultInstance()) {
          result.position_ =
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.newBuilder(result.position_).mergeFrom(value).buildPartial();
        } else {
          result.position_ = value;
        }
        result.hasPosition = true;
        return this;
      }
      public Builder clearPosition() {
        result.hasPosition = false;
        result.position_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.getDefaultInstance();
        return this;
      }
      
      // optional .uk.ac.ed.inf.sdp.group4.WorldObject.Vector vector = 2;
      public boolean hasVector() {
        return result.hasVector();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector getVector() {
        return result.getVector();
      }
      public Builder setVector(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasVector = true;
        result.vector_ = value;
        return this;
      }
      public Builder setVector(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.Builder builderForValue) {
        result.hasVector = true;
        result.vector_ = builderForValue.build();
        return this;
      }
      public Builder mergeVector(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector value) {
        if (result.hasVector() &&
            result.vector_ != uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.getDefaultInstance()) {
          result.vector_ =
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.newBuilder(result.vector_).mergeFrom(value).buildPartial();
        } else {
          result.vector_ = value;
        }
        result.hasVector = true;
        return this;
      }
      public Builder clearVector() {
        result.hasVector = false;
        result.vector_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:uk.ac.ed.inf.sdp.group4.WorldObject)
    }
    
    static {
      defaultInstance = new WorldObject(true);
      uk.ac.ed.inf.sdp.group4.Worldstate.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:uk.ac.ed.inf.sdp.group4.WorldObject)
  }
  
  public static final class WorldStateResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use WorldStateResponse.newBuilder() to construct.
    private WorldStateResponse() {
      initFields();
    }
    private WorldStateResponse(boolean noInit) {}
    
    private static final WorldStateResponse defaultInstance;
    public static WorldStateResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public WorldStateResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_fieldAccessorTable;
    }
    
    // required bool changed = 1;
    public static final int CHANGED_FIELD_NUMBER = 1;
    private boolean hasChanged;
    private boolean changed_ = false;
    public boolean hasChanged() { return hasChanged; }
    public boolean getChanged() { return changed_; }
    
    // required uint64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // optional .uk.ac.ed.inf.sdp.group4.WorldObject ball = 3;
    public static final int BALL_FIELD_NUMBER = 3;
    private boolean hasBall;
    private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject ball_;
    public boolean hasBall() { return hasBall; }
    public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getBall() { return ball_; }
    
    // optional .uk.ac.ed.inf.sdp.group4.WorldObject blue = 4;
    public static final int BLUE_FIELD_NUMBER = 4;
    private boolean hasBlue;
    private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject blue_;
    public boolean hasBlue() { return hasBlue; }
    public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getBlue() { return blue_; }
    
    // optional .uk.ac.ed.inf.sdp.group4.WorldObject yellow = 5;
    public static final int YELLOW_FIELD_NUMBER = 5;
    private boolean hasYellow;
    private uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject yellow_;
    public boolean hasYellow() { return hasYellow; }
    public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getYellow() { return yellow_; }
    
    private void initFields() {
      ball_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
      blue_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
      yellow_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasChanged) return false;
      if (!hasTimestamp) return false;
      if (hasBall()) {
        if (!getBall().isInitialized()) return false;
      }
      if (hasBlue()) {
        if (!getBlue().isInitialized()) return false;
      }
      if (hasYellow()) {
        if (!getYellow().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasChanged()) {
        output.writeBool(1, getChanged());
      }
      if (hasTimestamp()) {
        output.writeUInt64(2, getTimestamp());
      }
      if (hasBall()) {
        output.writeMessage(3, getBall());
      }
      if (hasBlue()) {
        output.writeMessage(4, getBlue());
      }
      if (hasYellow()) {
        output.writeMessage(5, getYellow());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasChanged()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getChanged());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, getTimestamp());
      }
      if (hasBall()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBall());
      }
      if (hasBlue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getBlue());
      }
      if (hasYellow()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getYellow());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse result;
      
      // Construct using uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse();
        return builder;
      }
      
      protected uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDescriptor();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse getDefaultInstanceForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse) {
          return mergeFrom((uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse other) {
        if (other == uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDefaultInstance()) return this;
        if (other.hasChanged()) {
          setChanged(other.getChanged());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasBall()) {
          mergeBall(other.getBall());
        }
        if (other.hasBlue()) {
          mergeBlue(other.getBlue());
        }
        if (other.hasYellow()) {
          mergeYellow(other.getYellow());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setChanged(input.readBool());
              break;
            }
            case 16: {
              setTimestamp(input.readUInt64());
              break;
            }
            case 26: {
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder subBuilder = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder();
              if (hasBall()) {
                subBuilder.mergeFrom(getBall());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBall(subBuilder.buildPartial());
              break;
            }
            case 34: {
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder subBuilder = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder();
              if (hasBlue()) {
                subBuilder.mergeFrom(getBlue());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBlue(subBuilder.buildPartial());
              break;
            }
            case 42: {
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder subBuilder = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder();
              if (hasYellow()) {
                subBuilder.mergeFrom(getYellow());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setYellow(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required bool changed = 1;
      public boolean hasChanged() {
        return result.hasChanged();
      }
      public boolean getChanged() {
        return result.getChanged();
      }
      public Builder setChanged(boolean value) {
        result.hasChanged = true;
        result.changed_ = value;
        return this;
      }
      public Builder clearChanged() {
        result.hasChanged = false;
        result.changed_ = false;
        return this;
      }
      
      // required uint64 timestamp = 2;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // optional .uk.ac.ed.inf.sdp.group4.WorldObject ball = 3;
      public boolean hasBall() {
        return result.hasBall();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getBall() {
        return result.getBall();
      }
      public Builder setBall(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasBall = true;
        result.ball_ = value;
        return this;
      }
      public Builder setBall(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder builderForValue) {
        result.hasBall = true;
        result.ball_ = builderForValue.build();
        return this;
      }
      public Builder mergeBall(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (result.hasBall() &&
            result.ball_ != uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance()) {
          result.ball_ =
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder(result.ball_).mergeFrom(value).buildPartial();
        } else {
          result.ball_ = value;
        }
        result.hasBall = true;
        return this;
      }
      public Builder clearBall() {
        result.hasBall = false;
        result.ball_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
        return this;
      }
      
      // optional .uk.ac.ed.inf.sdp.group4.WorldObject blue = 4;
      public boolean hasBlue() {
        return result.hasBlue();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getBlue() {
        return result.getBlue();
      }
      public Builder setBlue(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasBlue = true;
        result.blue_ = value;
        return this;
      }
      public Builder setBlue(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder builderForValue) {
        result.hasBlue = true;
        result.blue_ = builderForValue.build();
        return this;
      }
      public Builder mergeBlue(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (result.hasBlue() &&
            result.blue_ != uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance()) {
          result.blue_ =
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder(result.blue_).mergeFrom(value).buildPartial();
        } else {
          result.blue_ = value;
        }
        result.hasBlue = true;
        return this;
      }
      public Builder clearBlue() {
        result.hasBlue = false;
        result.blue_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
        return this;
      }
      
      // optional .uk.ac.ed.inf.sdp.group4.WorldObject yellow = 5;
      public boolean hasYellow() {
        return result.hasYellow();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject getYellow() {
        return result.getYellow();
      }
      public Builder setYellow(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasYellow = true;
        result.yellow_ = value;
        return this;
      }
      public Builder setYellow(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder builderForValue) {
        result.hasYellow = true;
        result.yellow_ = builderForValue.build();
        return this;
      }
      public Builder mergeYellow(uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject value) {
        if (result.hasYellow() &&
            result.yellow_ != uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance()) {
          result.yellow_ =
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.newBuilder(result.yellow_).mergeFrom(value).buildPartial();
        } else {
          result.yellow_ = value;
        }
        result.hasYellow = true;
        return this;
      }
      public Builder clearYellow() {
        result.hasYellow = false;
        result.yellow_ = uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:uk.ac.ed.inf.sdp.group4.WorldStateResponse)
    }
    
    static {
      defaultInstance = new WorldStateResponse(true);
      uk.ac.ed.inf.sdp.group4.Worldstate.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:uk.ac.ed.inf.sdp.group4.WorldStateResponse)
  }
  
  public static final class WorldStateRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use WorldStateRequest.newBuilder() to construct.
    private WorldStateRequest() {
      initFields();
    }
    private WorldStateRequest(boolean noInit) {}
    
    private static final WorldStateRequest defaultInstance;
    public static WorldStateRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public WorldStateRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_fieldAccessorTable;
    }
    
    // required uint64 last_timestamp = 1;
    public static final int LAST_TIMESTAMP_FIELD_NUMBER = 1;
    private boolean hasLastTimestamp;
    private long lastTimestamp_ = 0L;
    public boolean hasLastTimestamp() { return hasLastTimestamp; }
    public long getLastTimestamp() { return lastTimestamp_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasLastTimestamp) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLastTimestamp()) {
        output.writeUInt64(1, getLastTimestamp());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLastTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getLastTimestamp());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest result;
      
      // Construct using uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest();
        return builder;
      }
      
      protected uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.getDescriptor();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest getDefaultInstanceForType() {
        return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest) {
          return mergeFrom((uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest other) {
        if (other == uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.getDefaultInstance()) return this;
        if (other.hasLastTimestamp()) {
          setLastTimestamp(other.getLastTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setLastTimestamp(input.readUInt64());
              break;
            }
          }
        }
      }
      
      
      // required uint64 last_timestamp = 1;
      public boolean hasLastTimestamp() {
        return result.hasLastTimestamp();
      }
      public long getLastTimestamp() {
        return result.getLastTimestamp();
      }
      public Builder setLastTimestamp(long value) {
        result.hasLastTimestamp = true;
        result.lastTimestamp_ = value;
        return this;
      }
      public Builder clearLastTimestamp() {
        result.hasLastTimestamp = false;
        result.lastTimestamp_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:uk.ac.ed.inf.sdp.group4.WorldStateRequest)
    }
    
    static {
      defaultInstance = new WorldStateRequest(true);
      uk.ac.ed.inf.sdp.group4.Worldstate.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:uk.ac.ed.inf.sdp.group4.WorldStateRequest)
  }
  
  public static abstract class WorldStateService
      implements com.google.protobuf.Service {
    protected WorldStateService() {}
    
    public interface Interface {
      public abstract void getWorldState(
          com.google.protobuf.RpcController controller,
          uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest request,
          com.google.protobuf.RpcCallback<uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new WorldStateService() {
        @Override
        public  void getWorldState(
            com.google.protobuf.RpcController controller,
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest request,
            com.google.protobuf.RpcCallback<uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse> done) {
          impl.getWorldState(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getWorldState(controller, (uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void getWorldState(
        com.google.protobuf.RpcController controller,
        uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest request,
        com.google.protobuf.RpcCallback<uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return uk.ac.ed.inf.sdp.group4.Worldstate.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getWorldState(controller, (uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest)request,
            com.google.protobuf.RpcUtil.<uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void getWorldState(
          com.google.protobuf.RpcController controller,
          uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest request,
          com.google.protobuf.RpcCallback<uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.class,
            uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse getWorldState(
          com.google.protobuf.RpcController controller,
          uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse getWorldState(
          com.google.protobuf.RpcController controller,
          uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest request)
          throws com.google.protobuf.ServiceException {
        return (uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Vector_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Vector_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020worldstate.proto\022\027uk.ac.ed.inf.sdp.gro" +
      "up4\"\334\001\n\013WorldObject\022?\n\010position\030\001 \002(\0132-." +
      "uk.ac.ed.inf.sdp.group4.WorldObject.Posi" +
      "tion\022;\n\006vector\030\002 \001(\0132+.uk.ac.ed.inf.sdp." +
      "group4.WorldObject.Vector\032 \n\010Position\022\t\n" +
      "\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005\032-\n\006Vector\022\021\n\tdirecti" +
      "on\030\001 \002(\005\022\020\n\010velocity\030\002 \001(\002\"\326\001\n\022WorldStat" +
      "eResponse\022\017\n\007changed\030\001 \002(\010\022\021\n\ttimestamp\030" +
      "\002 \002(\004\0222\n\004ball\030\003 \001(\0132$.uk.ac.ed.inf.sdp.g" +
      "roup4.WorldObject\0222\n\004blue\030\004 \001(\0132$.uk.ac.",
      "ed.inf.sdp.group4.WorldObject\0224\n\006yellow\030" +
      "\005 \001(\0132$.uk.ac.ed.inf.sdp.group4.WorldObj" +
      "ect\"+\n\021WorldStateRequest\022\026\n\016last_timesta" +
      "mp\030\001 \002(\0042}\n\021WorldStateService\022h\n\rGetWorl" +
      "dState\022*.uk.ac.ed.inf.sdp.group4.WorldSt" +
      "ateRequest\032+.uk.ac.ed.inf.sdp.group4.Wor" +
      "ldStateResponseB\006\210\001\001\220\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor,
              new java.lang.String[] { "Position", "Vector", },
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.class,
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Builder.class);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_descriptor =
            internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor.getNestedTypes().get(0);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Position_descriptor,
              new java.lang.String[] { "X", "Y", },
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.class,
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Position.Builder.class);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Vector_descriptor =
            internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_descriptor.getNestedTypes().get(1);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Vector_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_uk_ac_ed_inf_sdp_group4_WorldObject_Vector_descriptor,
              new java.lang.String[] { "Direction", "Velocity", },
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.class,
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldObject.Vector.Builder.class);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_uk_ac_ed_inf_sdp_group4_WorldStateResponse_descriptor,
              new java.lang.String[] { "Changed", "Timestamp", "Ball", "Blue", "Yellow", },
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.class,
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateResponse.Builder.class);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_uk_ac_ed_inf_sdp_group4_WorldStateRequest_descriptor,
              new java.lang.String[] { "LastTimestamp", },
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.class,
              uk.ac.ed.inf.sdp.group4.Worldstate.WorldStateRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
